---
# nginx role vars
nginx_remove_default_vhost: true

nginx_upstreams:
  - name: frontend.app
    strategy: "least_conn"
    keepalive: 16 # optional
    servers: {
      "localhost:8080",
      "localhost:8081",
      "localhost:8082"
    }
  - name: backend.app
    strategy: "least_conn"
    keepalive: 16 # optional
    servers: {
      "localhost:8083",
      "localhost:8084",
      "localhost:8085"
    }

nginx_vhosts:
  - server_name: "frontend.redirect" 
    listen: "80"
    extra_parameters: |
      return 301 https://$host$request_uri;
  - server_name: "frontend.https" 
    listen: "443 ssl http2"

    extra_parameters: |
      access_log  /home/vagrant/app/log/frontend-upstream-access.log;
      error_log   /home/vagrant/app/log/frontend-upstream-error.log;

      location / {
          proxy_pass http://frontend.app;
      }

      ssl_certificate     /etc/ssl/certs/nginx-selfsigned.crt;
      ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

  - server_name: "backend.https" 
    listen: "8000"
    extra_parameters: |
      access_log  /home/vagrant/app/log/backend-upstream-access.log;
      error_log   /home/vagrant/app/log/backend-upstream-error.log;

      location / {
          proxy_pass http://backend.app;
      }

  - server_name: "frontend.app.dev" 
    listen: "8080"
    root: "/home/vagrant/app/frontend/web/"
    index: "index.php"
    filename: "frontend.app.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app/log/frontend-app-access.log;
      error_log   /home/vagrant/app/log/frontend-app-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }
  - server_name: "frontend.app1.dev" 
    listen: "8081"
    root: "/home/vagrant/app1/frontend/web/"
    index: "index.php"
    filename: "frontend.app1.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app1/log/frontend-app1-access.log;
      error_log   /home/vagrant/app1/log/frontend-app1-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }
  - server_name: "frontend.app2.dev" 
    listen: "8082"
    root: "/home/vagrant/app2/frontend/web/"
    index: "index.php"
    filename: "frontend.app2.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app2/log/frontend-app2-access.log;
      error_log   /home/vagrant/app2/log/frontend-app2-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }

  - server_name: "backend.app.dev" 
    listen: "8083"
    root: "/home/vagrant/app/backend/web/"
    index: "index.php"
    filename: "backend.app.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app/log/backend-app-access.log;
      error_log   /home/vagrant/app/log/backend-app-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }
  - server_name: "backend.app1.dev" 
    listen: "8084"
    root: "/home/vagrant/app1/backend/web/"
    index: "index.php"
    filename: "backend.app1.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app1/log/backend-app1-access.log;
      error_log   /home/vagrant/app1/log/backend-app1-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }
  - server_name: "backend.app2.dev" 
    listen: "8085"
    root: "/home/vagrant/app2/backend/web/"
    index: "index.php"
    filename: "backend.app2.dev.conf"   
    extra_parameters: |
      charset utf-8;
      client_max_body_size 128M;

      access_log  /home/vagrant/app2/log/backend-app2-access.log;
      error_log   /home/vagrant/app2/log/backend-app2-error.log;

      location / {
          # Redirect everything that isn't a real file to index.php
          try_files $uri $uri/ /index.php$is_args$args;
      }

      # uncomment to avoid processing of calls to non-existing static files by Yii
      #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
      #    try_files $uri =404;
      #}
      #error_page 404 /404.html;

      # deny accessing php files for the /assets directory
      location ~ ^/assets/.*\.php$ {
          deny all;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          #fastcgi_pass unix:/var/run/php7.0-fpm.sock;
          try_files $uri =404;
      }
     
      location ~* /\. {
          deny all;
      }

  

# php role vars

# memcache role vars

memcached_log_verbosity: "-v"