---
# nginx role vars
nginx_remove_default_vhost: true

nginx_upstreams:
  - name: app-frontend.com
    strategy: "ip_hash"
    keepalive: 16 # optional
    servers: {
      "192.168.33.29:80",
      "192.168.33.30:80",
    }

nginx_vhosts:
  - server_name: "frontend.redirect" 
    listen: "80"
    extra_parameters: |
      return 301 https://$host$request_uri;
  - server_name: "frontend.https" 
    listen: "443 ssl http2"

    extra_parameters: |
      access_log  /home/vagrant/log/frontend-upstream-access.log;
      error_log   /home/vagrant/log/frontend-upstream-error.log;

      location / {
          proxy_pass http://app-frontend.com;
      }

      ssl_certificate     /etc/ssl/certs/nginx-selfsigned.crt;
      ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

