---
- hosts: db-master
  remote_user: vagrant
  become: yes
  tasks:
    - name: Init database
      command: >
        sudo mysql -u root --execute="source SQL_scripts/init_db.sql; "

- hosts: apps
  remote_user: vagrant
  become: yes
  tasks:
    - name: init yii advanced project
      command: php /home/vagrant/app/init --env=Development --overwrite=n
      register: log

    - name: Debug
      debug: var=log.stdout_lines
      
    - name: install composer vendors
      command: /usr/local/bin/composer install -d /home/vagrant/app
      register: log

    - name: Debug
      debug: var=log.stdout_lines

    - name: excute init command
      command: php /home/vagrant/app/yii init
      register: log
    
    - name: Debug
      debug: var=log.stdout_lines

    
     