---
- hosts: apps
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: init yii advanced project
      command: php /home/vagrant/app/init --env=Development --overwrite=n
      register: log

    - name: Debug
      debug: var=log.stdout_lines
      
    - name: install composer vendors
      command: /usr/local/bin/composer install -d /home/vagrant/app
      register: log

    - name: Debug
      debug: var=log.stdout_lines
    
- hosts: db
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Create Database
      command: >
        sudo mysql -u root --execute="CREATE DATABASE IF NOT EXISTS mockProject CHARACTER SET utf8 COLLATE utf8_general_ci;"
    - name: Refresh and create Tables
      command: >
        sudo mysql -u root --execute="source SQL_scripts/init_db.sql; "

    
     