---
- name: Installed required packages and config apps
  hosts: apps
  tags: apps-packages
  remote_user: vagrant
  become: yes
  vars_files: 
    - vars/apps.yml
  roles: 
    - app.ssl-install
    - geerlingguy.nginx
    - geerlingguy.git
    - geerlingguy.repo-remi
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.memcached
  tasks:
    - include_tasks: "tasks/apps-config.yml"

- name: Installed required packages and create privileges on db master and db slaves
  hosts: db
  tags: database-packages
  remote_user: vagrant
  become: yes
  roles:
    - geerlingguy.mysql
  tasks:
    - include_tasks: "tasks/db-config.yml"

- name: config db master
  hosts: db-master
  remote_user: vagrant
  become: yes
  tags: config-master
  tasks:
    - include_tasks: "tasks/db-master-config.yml"

- name: config db-slaves
  hosts: db-slaves
  tags: config-slaves
  remote_user: vagrant
  become: yes 
  tasks:
    - include_tasks: "tasks/db-slaves-config.yml"    

    
     