---
- src: geerlingguy.nginx
  version: "2.6.0"

- src: geerlingguy.php
  version: "3.6.0"

- src: geerlingguy.repo-remi
  version: "1.2.0"
  
- src: geerlingguy.mysql
  version: "2.9.0"

- src: geerlingguy.memcached
  version: "1.0.8"

- src: geerlingguy.php-versions
  version: "2.1.3"

- src: geerlingguy.php-mysql
  version: "2.0.1"

- src: geerlingguy.git
  version: "2.0.2"

- src: geerlingguy.composer
  version: "1.7.0"