---
- name: Check config file was configured or not"
  command: grep -Fxq "# Logging configuration." /etc/my.cnf
  register: checkmyconf
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: change file my.cnf 
  lineinfile:
    dest: "/etc/my.cnf"
    regexp: "# Logging configuration."
    line: "server-id=1\nlog_bin=/var/log/mariadb/mariadb-bin.log\nbinlog_do_db={{ db_name }}"
  when: checkmyconf.rc == 0

- name: Restart service mariadb (mysql)
  service:
    name: mariadb
    state: restarted

- name: grant replication slave
  command: >
    sudo mysql -u root --execute="grant replication slave on *.* to {{ master_user }}@'%' identified by '{{ master_password}}'; flush privileges;"

- name: dump database 
  command: >
    sudo mysqldump -u root {{ db_name }} -r SQL_scripts/{{ db_name}}.sql

