---
- name: Check config file was configured or not"
  command: grep -Fxq "# Logging configuration." /etc/my.cnf
  register: checkmyconf
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Config slave my.cnf
  lineinfile:
    dest: "/etc/my.cnf"
    regexp: "# Logging configuration."
    line: "server-id={{ slave_count_id }}\nrelay-log=/var/log/mariadb/mariadb-relay-bin.log\nbinlog_do_db={{db_name}}"
  when: checkmyconf.rc == 0

- name: Restart service mariadb (mysql)
  service:
    name: mariadb
    state: restarted

- name: sync database
  command: >
    sudo mysql -u root -D {{ db_name }} --execute="source SQL_scripts/{{ db_name }}.sql;"

- name: Check master replication status.
  mysql_replication: mode=getmaster
  delegate_to: "db-master1"
  register: master

- name: stop slave
  command: >
    sudo mysql -u root --execute="stop slave;"

- name: reset slave
  command: >
    sudo mysql -u root --execute="reset slave;"

- name: config replication slave
  command: >
    sudo mysql -u root --execute="CHANGE MASTER TO MASTER_HOST='192.168.33.27',MASTER_USER='{{ master_user}}', MASTER_PASSWORD='{{ master_password }}', MASTER_LOG_FILE='{{ master.File }}', MASTER_LOG_POS= {{ master.Position}};"

- name: start slave
  command: >
    sudo mysql -u root --execute="start slave;"